/*
 * Notes
 * Backend app with Notes and Notetasks
 *
 * OpenAPI spec version: 1.0
 * Contact: staske11111@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CategoryDto} from './CategoryDto';

/**
 * The CategoryListDto model module.
 * @module model/CategoryListDto
 * @version 1.0
 */
export class CategoryListDto {
  /**
   * Constructs a new <code>CategoryListDto</code>.
   * @alias module:model/CategoryListDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CategoryListDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CategoryListDto} obj Optional instance to populate.
   * @return {module:model/CategoryListDto} The populated <code>CategoryListDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CategoryListDto();
      if (data.hasOwnProperty('categories'))
        obj.categories = ApiClient.convertToType(data['categories'], [CategoryDto]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/CategoryDto>} categories
 */
CategoryListDto.prototype.categories = undefined;

