/*
 * Notes
 * Backend app with Notes and Notetasks
 *
 * OpenAPI spec version: 1.0
 * Contact: staske11111@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateNoteVm model module.
 * @module model/CreateNoteVm
 * @version 1.0
 */
export class CreateNoteVm {
  /**
   * Constructs a new <code>CreateNoteVm</code>.
   * @alias module:model/CreateNoteVm
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateNoteVm</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateNoteVm} obj Optional instance to populate.
   * @return {module:model/CreateNoteVm} The populated <code>CreateNoteVm</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateNoteVm();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
      if (data.hasOwnProperty('categoryId'))
        obj.categoryId = ApiClient.convertToType(data['categoryId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
CreateNoteVm.prototype.name = undefined;

/**
 * @member {String} text
 */
CreateNoteVm.prototype.text = undefined;

/**
 * @member {String} categoryId
 */
CreateNoteVm.prototype.categoryId = undefined;

