/*
 * Notes
 * Backend app with Notes and Notetasks
 *
 * OpenAPI spec version: 1.0
 * Contact: staske11111@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MatrixDto} from './MatrixDto';

/**
 * The MatrixListDto model module.
 * @module model/MatrixListDto
 * @version 1.0
 */
export class MatrixListDto {
  /**
   * Constructs a new <code>MatrixListDto</code>.
   * @alias module:model/MatrixListDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MatrixListDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MatrixListDto} obj Optional instance to populate.
   * @return {module:model/MatrixListDto} The populated <code>MatrixListDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MatrixListDto();
      if (data.hasOwnProperty('matrices'))
        obj.matrices = ApiClient.convertToType(data['matrices'], [MatrixDto]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/MatrixDto>} matrices
 */
MatrixListDto.prototype.matrices = undefined;

