/*
 * Notes
 * Backend app with Notes and Notetasks
 *
 * OpenAPI spec version: 1.0
 * Contact: staske11111@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {NoteTaskDto} from './NoteTaskDto';

/**
 * The NoteTaskListDto model module.
 * @module model/NoteTaskListDto
 * @version 1.0
 */
export class NoteTaskListDto {
  /**
   * Constructs a new <code>NoteTaskListDto</code>.
   * @alias module:model/NoteTaskListDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>NoteTaskListDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NoteTaskListDto} obj Optional instance to populate.
   * @return {module:model/NoteTaskListDto} The populated <code>NoteTaskListDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NoteTaskListDto();
      if (data.hasOwnProperty('tasks'))
        obj.tasks = ApiClient.convertToType(data['tasks'], [NoteTaskDto]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/NoteTaskDto>} tasks
 */
NoteTaskListDto.prototype.tasks = undefined;

