/*
 * Notes
 * Backend app with Notes and Notetasks
 *
 * OpenAPI spec version: 1.0
 * Contact: staske11111@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The NoteDto model module.
 * @module model/NoteDto
 * @version 1.0
 */
export class NoteDto {
  /**
   * Constructs a new <code>NoteDto</code>.
   * @alias module:model/NoteDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>NoteDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NoteDto} obj Optional instance to populate.
   * @return {module:model/NoteDto} The populated <code>NoteDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NoteDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
NoteDto.prototype.id = undefined;

/**
 * @member {String} name
 */
NoteDto.prototype.name = undefined;

