/*
 * Notes
 * Backend app with Notes and Notetasks
 *
 * OpenAPI spec version: 1.0
 * Contact: staske11111@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MatricesEnum} from './MatricesEnum';
import {ProgressConditionEnum} from './ProgressConditionEnum';

/**
 * The NoteTaskDetailsDto model module.
 * @module model/NoteTaskDetailsDto
 * @version 1.0
 */
export class NoteTaskDetailsDto {
  /**
   * Constructs a new <code>NoteTaskDetailsDto</code>.
   * @alias module:model/NoteTaskDetailsDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>NoteTaskDetailsDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NoteTaskDetailsDto} obj Optional instance to populate.
   * @return {module:model/NoteTaskDetailsDto} The populated <code>NoteTaskDetailsDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NoteTaskDetailsDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
      if (data.hasOwnProperty('seconds'))
        obj.seconds = ApiClient.convertToType(data['seconds'], 'Number');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('matrixId'))
        obj.matrixId = MatricesEnum.constructFromObject(data['matrixId']);
      if (data.hasOwnProperty('progressConditionId'))
        obj.progressConditionId = ProgressConditionEnum.constructFromObject(data['progressConditionId']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
NoteTaskDetailsDto.prototype.id = undefined;

/**
 * @member {String} name
 */
NoteTaskDetailsDto.prototype.name = undefined;

/**
 * @member {String} text
 */
NoteTaskDetailsDto.prototype.text = undefined;

/**
 * @member {Number} seconds
 */
NoteTaskDetailsDto.prototype.seconds = undefined;

/**
 * @member {Date} _date
 */
NoteTaskDetailsDto.prototype._date = undefined;

/**
 * @member {module:model/MatricesEnum} matrixId
 */
NoteTaskDetailsDto.prototype.matrixId = undefined;

/**
 * @member {module:model/ProgressConditionEnum} progressConditionId
 */
NoteTaskDetailsDto.prototype.progressConditionId = undefined;

