/*
 * Notes
 * Backend app with Notes and Notetasks
 *
 * OpenAPI spec version: 1.4.0
 * Contact: staske11111@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UpdateNoteVm model module.
 * @module model/UpdateNoteVm
 * @version 1.4.0
 */
export class UpdateNoteVm {
  /**
   * Constructs a new <code>UpdateNoteVm</code>.
   * @alias module:model/UpdateNoteVm
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UpdateNoteVm</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateNoteVm} obj Optional instance to populate.
   * @return {module:model/UpdateNoteVm} The populated <code>UpdateNoteVm</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateNoteVm();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
UpdateNoteVm.prototype.id = undefined;

/**
 * @member {String} name
 */
UpdateNoteVm.prototype.name = undefined;

/**
 * @member {String} text
 */
UpdateNoteVm.prototype.text = undefined;

