/*
 * Notes
 * Backend app with Notes and Notetasks
 *
 * OpenAPI spec version: 1.0
 * Contact: staske11111@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {CategoryDto} from './model/CategoryDto';
import {CategoryListDto} from './model/CategoryListDto';
import {CreateCategoryVm} from './model/CreateCategoryVm';
import {CreateNoteTaskVm} from './model/CreateNoteTaskVm';
import {CreateNoteVm} from './model/CreateNoteVm';
import {MatricesEnum} from './model/MatricesEnum';
import {MatrixDto} from './model/MatrixDto';
import {MatrixListDto} from './model/MatrixListDto';
import {NoteDetailsDto} from './model/NoteDetailsDto';
import {NoteDto} from './model/NoteDto';
import {NoteListDto} from './model/NoteListDto';
import {NoteTaskDetailsDto} from './model/NoteTaskDetailsDto';
import {NoteTaskDto} from './model/NoteTaskDto';
import {NoteTaskListDto} from './model/NoteTaskListDto';
import {Operation} from './model/Operation';
import {OperationType} from './model/OperationType';
import {ProblemDetails} from './model/ProblemDetails';
import {ProgressConditionDto} from './model/ProgressConditionDto';
import {ProgressConditionEnum} from './model/ProgressConditionEnum';
import {ProgressConditionListDto} from './model/ProgressConditionListDto';
import {UpdateCategoryVm} from './model/UpdateCategoryVm';
import {UpdateNoteTaskVm} from './model/UpdateNoteTaskVm';
import {UpdateNoteVm} from './model/UpdateNoteVm';
import {CategoryApi} from './api/CategoryApi';
import {MatrixApi} from './api/MatrixApi';
import {NoteApi} from './api/NoteApi';
import {NoteTaskApi} from './api/NoteTaskApi';
import {ProgressConditionApi} from './api/ProgressConditionApi';

/**
* Backend_app_with_Notes_and_Notetasks.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Notes = require('index'); // See note below*.
* var xxxSvc = new Notes.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Notes.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Notes.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Notes.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CategoryDto model constructor.
     * @property {module:model/CategoryDto}
     */
    CategoryDto,

    /**
     * The CategoryListDto model constructor.
     * @property {module:model/CategoryListDto}
     */
    CategoryListDto,

    /**
     * The CreateCategoryVm model constructor.
     * @property {module:model/CreateCategoryVm}
     */
    CreateCategoryVm,

    /**
     * The CreateNoteTaskVm model constructor.
     * @property {module:model/CreateNoteTaskVm}
     */
    CreateNoteTaskVm,

    /**
     * The CreateNoteVm model constructor.
     * @property {module:model/CreateNoteVm}
     */
    CreateNoteVm,

    /**
     * The MatricesEnum model constructor.
     * @property {module:model/MatricesEnum}
     */
    MatricesEnum,

    /**
     * The MatrixDto model constructor.
     * @property {module:model/MatrixDto}
     */
    MatrixDto,

    /**
     * The MatrixListDto model constructor.
     * @property {module:model/MatrixListDto}
     */
    MatrixListDto,

    /**
     * The NoteDetailsDto model constructor.
     * @property {module:model/NoteDetailsDto}
     */
    NoteDetailsDto,

    /**
     * The NoteDto model constructor.
     * @property {module:model/NoteDto}
     */
    NoteDto,

    /**
     * The NoteListDto model constructor.
     * @property {module:model/NoteListDto}
     */
    NoteListDto,

    /**
     * The NoteTaskDetailsDto model constructor.
     * @property {module:model/NoteTaskDetailsDto}
     */
    NoteTaskDetailsDto,

    /**
     * The NoteTaskDto model constructor.
     * @property {module:model/NoteTaskDto}
     */
    NoteTaskDto,

    /**
     * The NoteTaskListDto model constructor.
     * @property {module:model/NoteTaskListDto}
     */
    NoteTaskListDto,

    /**
     * The Operation model constructor.
     * @property {module:model/Operation}
     */
    Operation,

    /**
     * The OperationType model constructor.
     * @property {module:model/OperationType}
     */
    OperationType,

    /**
     * The ProblemDetails model constructor.
     * @property {module:model/ProblemDetails}
     */
    ProblemDetails,

    /**
     * The ProgressConditionDto model constructor.
     * @property {module:model/ProgressConditionDto}
     */
    ProgressConditionDto,

    /**
     * The ProgressConditionEnum model constructor.
     * @property {module:model/ProgressConditionEnum}
     */
    ProgressConditionEnum,

    /**
     * The ProgressConditionListDto model constructor.
     * @property {module:model/ProgressConditionListDto}
     */
    ProgressConditionListDto,

    /**
     * The UpdateCategoryVm model constructor.
     * @property {module:model/UpdateCategoryVm}
     */
    UpdateCategoryVm,

    /**
     * The UpdateNoteTaskVm model constructor.
     * @property {module:model/UpdateNoteTaskVm}
     */
    UpdateNoteTaskVm,

    /**
     * The UpdateNoteVm model constructor.
     * @property {module:model/UpdateNoteVm}
     */
    UpdateNoteVm,

    /**
    * The CategoryApi service constructor.
    * @property {module:api/CategoryApi}
    */
    CategoryApi,

    /**
    * The MatrixApi service constructor.
    * @property {module:api/MatrixApi}
    */
    MatrixApi,

    /**
    * The NoteApi service constructor.
    * @property {module:api/NoteApi}
    */
    NoteApi,

    /**
    * The NoteTaskApi service constructor.
    * @property {module:api/NoteTaskApi}
    */
    NoteTaskApi,

    /**
    * The ProgressConditionApi service constructor.
    * @property {module:api/ProgressConditionApi}
    */
    ProgressConditionApi
};
