/*
 * Notes
 * Backend app with Notes and Notetasks
 *
 * OpenAPI spec version: 1.0
 * Contact: staske11111@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Notes);
  }
}(this, function(expect, Notes) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Notes.NoteApi();
  });

  describe('(package)', function() {
    describe('NoteApi', function() {
      describe('createNote', function() {
        it('should call createNote successfully', function(done) {
          // TODO: uncomment, update parameter values for createNote call and complete the assertions
          /*
          var opts = {};

          instance.createNote(apiVersion, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(&#x27;string&#x27;);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteNote', function() {
        it('should call deleteNote successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteNote call
          /*

          instance.deleteNote(id, apiVersion, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getNoteById', function() {
        it('should call getNoteById successfully', function(done) {
          // TODO: uncomment, update parameter values for getNoteById call and complete the assertions
          /*

          instance.getNoteById(id, apiVersion, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Notes.NoteDetailsDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getNotes', function() {
        it('should call getNotes successfully', function(done) {
          // TODO: uncomment, update parameter values for getNotes call and complete the assertions
          /*

          instance.getNotes(apiVersion, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Notes.NoteListDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getNotesByCategoryId', function() {
        it('should call getNotesByCategoryId successfully', function(done) {
          // TODO: uncomment, update parameter values for getNotesByCategoryId call and complete the assertions
          /*

          instance.getNotesByCategoryId(id, apiVersion, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Notes.NoteListDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateNote', function() {
        it('should call updateNote successfully', function(done) {
          // TODO: uncomment, update parameter values for updateNote call
          /*
          var opts = {};

          instance.updateNote(apiVersion, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
